<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-GrpcServer-66e9252a-425e-46ba-933c-35f116550e8d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.65.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\greeter.proto" GrpcServices="Server" />
  </ItemGroup>
</Project>
